### ISSUE TITLE
imshow_hs crashes with matplotlib2.0

### ISSUE THREAD

**Issue by craigmillernz** [jobar8/graphics#1]
I've been using your fantastic imshow_hs function.  I recently upgraded to matplotlib2.0 and now when I run a script using imshow_hs it crashes python.  I've reverted back to matplotlib 1.5.3 which fixes the problem.  Have you tried this one matplotlib2.0?
Thanks

**Comment by jobar8** [comment]
Hi,
There are a few updates to imshow_hs I haven't applied yet. So I am going to work on these and make sure they are compatible with Matplotlib 2.0. 
Watch this space!
Joseph

**Comment by craigmillernz** [comment]
Thanks!

**Comment by jobar8** [comment]
Hi Craig,
I ran the notebook again with matplotlib 2.0 (and Python 3.5) and it seems to be working fine, _once_ you use the correct parameter `cmap_norm `(it used to be called `norm_cmap`). 
I have updated the notebook, but not the function. The other updates I was talking about earlier will be introduced in a completely new module along side lots of other stuff.
Cheers.

**Comment by craigmillernz** [comment]
Hi


Ok thanks for that, I'll check what I have.  FYI, I'm still using python 2.7, planning to shift to 3.x in the next year I hope.


I'll look forward to future updates and new stuff [😊]

Regards

Craig



________________________________
